name: dnd_music
description: Project flutter UAS.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^1.3.3
  lottie: ^1.2.1 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/artists/
    - assets/images/
    - assets/lottie/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Product Sans
      fonts:
        - asset: assets/fonts/ProductSans/psans.ttf
